// Centralized icon set (lucide-react, Feather-style line icons) so screen and
// shell components pull from one place. The design recommends lucide-react and
// equivalents exist for every glyph the mockups use.
export {
  Building2,
  Wallet,
  Landmark,
  Coins,
  Receipt,
  PieChart,
  User,
  Inbox,
  ListChecks,
  Upload,
  TrendingUp,
  CheckCircle2,
  AlertTriangle,
  Calendar,
  Search,
  ChevronLeft,
  ChevronRight,
  Lock,
  Unlock,
  Copy,
  Trash2,
  Sun,
  Moon,
  Menu,
  LogOut,
  LayoutDashboard,
  FileText,
  Plus,
  X,
} from "lucide-react";
